/* This header file machine-generated by mktyplib.exe */
/* Interface to type library: WindowTypes */

#ifndef _WindowTypes_H_
#define _WindowTypes_H_

DEFINE_GUID(LIBID_WindowTypes,0x522EAF21,0xCB4B,0x11CE,0xA1,0xEC,0x44,0x45,0x53,0x54,0x00,0x00);

typedef unsigned long DWORD;

typedef long BOOL;

typedef unsigned short WORD;

typedef unsigned char BYTE;

typedef long LONG;

typedef unsigned long ULONG;

typedef double DWORDLONG;

typedef void FAR* HANDLE;

typedef HANDLE HPALETTE;

typedef HANDLE HDC;

typedef HANDLE FAR* HMENU;

typedef HANDLE FAR* WND;

typedef DWORD COLORREF;

typedef void FAR* LPVOID;

typedef void FAR* LPUNKNOWN;

typedef void FAR* LPSTREAM;

typedef char FAR* LPCTSTR;

typedef char FAR* LPCSTR;

typedef void FAR* PAVISTREAM;

typedef void FAR* LPDSBUFFERDESC;

typedef void FAR* LPDIRECTSOUNDBUFFER;

typedef void FAR* LPDDSURFACEDESC;

typedef void FAR* LPDIRECTDRAWSURFACE;

typedef void FAR* LPDIRECTDRAWPALETTE;

typedef struct _RECT {
    long left;
    long top;
    long right;
    long bottom;
} tagRECT;

typedef struct _RECT RECT;

typedef struct _tagAVISTREAMINFO {
    DWORD fccType;
    DWORD fccHandler;
    DWORD dwFlags;
    DWORD dwCaps;
    WORD wPriority;
    WORD wLanguage;
    DWORD dwScale;
    DWORD dwRate;
    DWORD dwStart;
    DWORD dwLength;
    DWORD dwInitialFrames;
    DWORD dwSuggestedBufferSize;
    DWORD dwQuality;
    DWORD dwSampleSize;
    RECT rcFrame;
    DWORD dwEditCount;
    DWORD dwFormatChangeCount;
    char szName[64];
} tagAVISTREAMINFO;

typedef struct _tagAVISTREAMINFO AVISTREAMINFO;

typedef struct _tagAVIFILEINFO {
    DWORD dwMaxBytesPerSec;
    DWORD dwFlags;
    DWORD dwCaps;
    DWORD dwStreams;
    DWORD dwSuggestedBufferSize;
    DWORD dwWidth;
    DWORD dwHeight;
    DWORD dwScale;
    DWORD dwRate;
    DWORD dwLength;
    DWORD dwEditCount;
    char szFileType[64];
} tagAVIFILEINFO;

typedef struct _tagAVIFILEINFO AVIFILEINFO;

typedef struct _tagULARGE_INTEGER {
    DWORD LowPart;
    DWORD HighPart;
} tagULARGE_INTEGER;

typedef struct _tagULARGE_INTEGER ULARGE_INTEGER;

typedef struct _tagCREATESTRUCT {
    LPVOID lpCreateParams;
    HANDLE hInstance;
    HMENU hMenu;
    WND hwndParent;
    int cy;
    int cx;
    int y;
    int x;
    long style;
    LPCTSTR lpszName;
    LPCTSTR lpszClass;
    DWORD dwExStyle;
} tagCREATESTRUCT;

typedef struct _tagCREATESTRUCT CREATESTRUCT;

typedef struct _tagRGBQUAD {
    BYTE rgbBlue;
    BYTE rgbGreen;
    BYTE rgbRed;
    BYTE rgbReserved;
} tagRGBQUAD;

typedef struct _tagRGBQUAD RGBQUAD;

typedef struct _tagBITMAPINFOHEADER {
    DWORD biSize;
    long biWidth;
    long biHeight;
    WORD biPlanes;
    WORD biBitCount;
    DWORD biCompression;
    DWORD biSizeImage;
    long biXPelsPerMeter;
    long biYPelsPerMeter;
    DWORD biClrUsed;
    DWORD biClrImportant;
} tagBITMAPINFOHEADER;

typedef struct _tagBITMAPINFOHEADER BITMAPINFOHEADER;

typedef struct _tagBITMAPINFO {
    BITMAPINFOHEADER bmiHeader;
    RGBQUAD bmiColors[1];
} tagBITMAPINFO;

typedef struct _tagBITMAPINFO BITMAPINFO;

typedef struct _tagGUID {
    DWORD Data1;
    WORD Data2;
    WORD Data3;
    BYTE Data4[8];
} tagGUID;

typedef struct _tagGUID GUID;

typedef GUID CLSID;

typedef CLSID FAR* LPCLSID;

typedef GUID IID;

typedef GUID FAR* REFGUID;

typedef IID FAR* REFIID;

typedef CLSID FAR* REFCLSID;

typedef struct _tagOBJECTID {
    GUID Lineage;
    unsigned long Uniquifier;
} TagOBJECTID;

typedef struct _tagOBJECTID OBJECTID;

#endif
